import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    HeaderContainer:{
        width: '100%',
        height: 72,
        borderWidth:2,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
    },
    HeaderText:{
        color:'white',
        fontFamily: 'Lexend-SemiBold',
        fontSize: 25,
    },
    BodyContainer:{
        flex: 1,
    },
    ScrollContainer:{
        paddingVertical: 8,
        paddingHorizontal: 12,
    },
    CardContainer:{
        width: '100%',
        height: 245,
        borderWidth:1,
        borderRadius:20,
        justifyContent:'center',
        alignItems: 'center',
        paddingHorizontal: 24,
        paddingVertical: 12,
        marginBottom: 12,
        backgroundColor: '#1F1F1F',
        elevation: 20,
    },
    CardTopContainer:{
        width: '100%',
        flexDirection: 'row',
        justifyContent:'space-between',
        paddingVertical: 10,
    },
    SettingIcon:{
        width: 30,
        height: 30,
    },
    mainText: {
        color: 'white',
        fontFamily: 'Lexend-Regular',
        fontWeight: 'medium',
        fontSize: 16,
    },
    HummidityContainer:{
        flexDirection: 'row',
        alignItems:'center',
        width: '100%',
        marginBottom: 4,
    },
    HummidityIcon:{
        color: 'white',
        marginRight: 8,
    },
    TemperatureIcon:{
        width: 24,
        height: 26,
        marginRight: 8,
    },
    StartButton:{
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
        height: 48,
        backgroundColor:'#17B55C',
        borderRadius:20,
        marginVertical:10,
    },
    InfoImageContainer:{
        width: '100%',
        height: 141,
        justifyContent: 'center',
        alignItems: 'center',
    },
    AnimalImage:{
        width: 100,
        height: 100,
        backgroundColor: 'white',
        borderRadius: 20,
    },
    AnimalSpecContainer:{
        width: '100%',
        height: 72,
        justifyContent: 'center',
    },
    SubText:{
        color: '#94C7AB',
        fontFamily: 'Lexend-Regular',
        fontSize: 14,
        lineHeight: 21,
    },
    TextInput:{
        width: '100%',
        height: 56,
        borderRadius: 12,
        backgroundColor: '#264533',
        padding: 16,
        fontFamily: 'Lexend-Regular',
        fontSize: 16,
        color: '#94C7AB',
        marginTop:8,
    },
    SetButton:{
        width: 84,
        height: 32,
        backgroundColor:'#264533',
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 10,
    },
    ChatgptButton:{
        paddingHorizontal: 12,
        paddingVertical: 4,
        backgroundColor:'white',
        justifyContent: 'center',
        alignItems:'center',
        flexDirection:'row',
        borderRadius: 20,
        alignSelf:'flex-end'
    },
    ChatgptLogo:{
        width: 30,
        height: 30,
    },
    ModalContainer:{
        flex: 1,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'rgba(0, 0, 0, 0.5)',
    },
    ChatgptModalContent:{
        width: '80%',
        borderRadius: 20,
        backgroundColor:'white',
        paddingHorizontal:24,
        paddingVertical: 24,
        justifyContent:'center',
        alignItems:'center',
    },
    ChatgptTextContainer:{
        justifyContent:'center',
        alignItems:'center',
        marginBottom: 24,
    },
    ChatgptModalText:{
        fontFamily: 'Lexend-Regular',
        color: '#94C7AB',    
    },
    ChatgptModalTextInput:{
        width: '100%',
        backgroundColor:'#264533',
        borderRadius: 12,
        color: '#94C7AB',
        fontFamily: 'Lexend-Regular',
        paddingHorizontal: 12,
    },
    GetDataButton:{
        width: 115,
        borderWidth: 1,
        borderRadius: 24,
        paddingVertical: 12,
        paddingHorizontal: 20,
        justifyContent:'center',
        alignItems:'center',
        backgroundColor:'white',
        elevation: 10,
    },
    MainText:{
        fontFamily: 'Lexend-Regular',
        color: 'black',
    },
    SetContent:{
        width: '100%',
        paddingHorizontal: 8,
        paddingVertical: 12,
        justifyContent: 'center',
        alignItems:'center',
    },
    SetIcon:{
        width: 40,
        height: 40,
        marginRight: 8,
    }
})
export default styles;